server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/UniCarDB
spring.datasource.username=usuario
spring.datasource.password=usuario
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#Validacion
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=unaClaveSecretaMuyLargaYSegura1234567890
jwt.expiration=86400000


#Log de la terminal organizado:

#Nombre y ubicacion de los logs
logging.file.name=logs/unicar.log

#Tama o maximo del log:
logging.logback.rollingpolicy.max-file-size=10MB

#Dias de historial guardados:
logging.logback.rollingpolicy.max-history=7

#Maximo total de archivos de log combinados
logging.logback.rollingpolicy.total-size-cap=100MB

#Codigo de los logs
logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{dd-MM-yyyy}.%i.gz